---
abstract: 'Test if your test covers all "public" subroutines of the package'
author:
  - 'Renee Baecker <module@renee-baecker.de>'
requires:
    Devel::Symdump:                0
    Exporter:                      0
    Hook::LexWrap:                 0
    Test::Builder:                 0
generated_by: ExtUtils::MakeMaker version 6.17
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
name: Test-TestCoverage
provides:
  Test::TestCoverage:
    file: /lib/Test/TestCoverage.pm
    version: 0.09
resources:
  license: http://dev.perl.org/licenses
version: 0.09
installdirs: site
